/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetSupportRouteImport } from './routes/get-support'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as UwCmsRouteImport } from './routes/uw-cms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as UwCmsIndexRouteImport } from './routes/uw-cms.index'
import { Route as UwCmsCategoriesRouteImport } from './routes/uw-cms.categories'
import { Route as UwCmsCommentsRouteImport } from './routes/uw-cms.comments'
import { Route as UwCmsLoginRouteImport } from './routes/uw-cms.login'
import { Route as UwCmsMediaRouteImport } from './routes/uw-cms.media'
import { Route as UwCmsBlogIndexRouteImport } from './routes/uw-cms/blog.index'
import { Route as UwCmsBlogNewRouteImport } from './routes/uw-cms/blog/new'
import { Route as UwCmsBlogIdEditRouteImport } from './routes/uw-cms/blog/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetSupportRoute = GetSupportRouteImport.update({
  id: '/get-support',
  path: '/get-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const UwCmsRoute = UwCmsRouteImport.update({
  id: '/uw-cms',
  path: '/uw-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const UwCmsIndexRoute = UwCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsCategoriesRoute = UwCmsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsCommentsRoute = UwCmsCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsLoginRoute = UwCmsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsMediaRoute = UwCmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsBlogIndexRoute = UwCmsBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsBlogNewRoute = UwCmsBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => UwCmsRoute,
} as any)
const UwCmsBlogIdEditRoute = UwCmsBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => UwCmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/get-support': typeof GetSupportRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/uw-cms': typeof UwCmsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/uw-cms/categories': typeof UwCmsCategoriesRoute
  '/uw-cms/comments': typeof UwCmsCommentsRoute
  '/uw-cms/login': typeof UwCmsLoginRoute
  '/uw-cms/media': typeof UwCmsMediaRoute
  '/blog/': typeof BlogIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/uw-cms/': typeof UwCmsIndexRoute
  '/uw-cms/blog/new': typeof UwCmsBlogNewRoute
  '/uw-cms/blog/': typeof UwCmsBlogIndexRoute
  '/uw-cms/blog/$id/edit': typeof UwCmsBlogIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-support': typeof GetSupportRoute
  '/resources': typeof ResourcesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/uw-cms/categories': typeof UwCmsCategoriesRoute
  '/uw-cms/comments': typeof UwCmsCommentsRoute
  '/uw-cms/login': typeof UwCmsLoginRoute
  '/uw-cms/media': typeof UwCmsMediaRoute
  '/blog': typeof BlogIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/uw-cms': typeof UwCmsIndexRoute
  '/uw-cms/blog/new': typeof UwCmsBlogNewRoute
  '/uw-cms/blog': typeof UwCmsBlogIndexRoute
  '/uw-cms/blog/$id/edit': typeof UwCmsBlogIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/get-support': typeof GetSupportRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/uw-cms': typeof UwCmsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/uw-cms/categories': typeof UwCmsCategoriesRoute
  '/uw-cms/comments': typeof UwCmsCommentsRoute
  '/uw-cms/login': typeof UwCmsLoginRoute
  '/uw-cms/media': typeof UwCmsMediaRoute
  '/blog/': typeof BlogIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/uw-cms/': typeof UwCmsIndexRoute
  '/uw-cms/blog/new': typeof UwCmsBlogNewRoute
  '/uw-cms/blog/': typeof UwCmsBlogIndexRoute
  '/uw-cms/blog/$id/edit': typeof UwCmsBlogIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/get-support'
    | '/programs'
    | '/resources'
    | '/stories'
    | '/uw-cms'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/stories/$slug'
    | '/uw-cms/categories'
    | '/uw-cms/comments'
    | '/uw-cms/login'
    | '/uw-cms/media'
    | '/blog/'
    | '/programs/'
    | '/stories/'
    | '/uw-cms/'
    | '/uw-cms/blog/new'
    | '/uw-cms/blog/'
    | '/uw-cms/blog/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/get-support'
    | '/resources'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/stories/$slug'
    | '/uw-cms/categories'
    | '/uw-cms/comments'
    | '/uw-cms/login'
    | '/uw-cms/media'
    | '/blog'
    | '/programs'
    | '/stories'
    | '/uw-cms'
    | '/uw-cms/blog/new'
    | '/uw-cms/blog'
    | '/uw-cms/blog/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/get-support'
    | '/programs'
    | '/resources'
    | '/stories'
    | '/uw-cms'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/stories/$slug'
    | '/uw-cms/categories'
    | '/uw-cms/comments'
    | '/uw-cms/login'
    | '/uw-cms/media'
    | '/blog/'
    | '/programs/'
    | '/stories/'
    | '/uw-cms/'
    | '/uw-cms/blog/new'
    | '/uw-cms/blog/'
    | '/uw-cms/blog/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GetSupportRoute: typeof GetSupportRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  UwCmsRoute: typeof UwCmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-support': {
      id: '/get-support'
      path: '/get-support'
      fullPath: '/get-support'
      preLoaderRoute: typeof GetSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uw-cms': {
      id: '/uw-cms'
      path: '/uw-cms'
      fullPath: '/uw-cms'
      preLoaderRoute: typeof UwCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/uw-cms/': {
      id: '/uw-cms/'
      path: '/'
      fullPath: '/uw-cms/'
      preLoaderRoute: typeof UwCmsIndexRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/categories': {
      id: '/uw-cms/categories'
      path: '/categories'
      fullPath: '/uw-cms/categories'
      preLoaderRoute: typeof UwCmsCategoriesRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/comments': {
      id: '/uw-cms/comments'
      path: '/comments'
      fullPath: '/uw-cms/comments'
      preLoaderRoute: typeof UwCmsCommentsRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/login': {
      id: '/uw-cms/login'
      path: '/login'
      fullPath: '/uw-cms/login'
      preLoaderRoute: typeof UwCmsLoginRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/media': {
      id: '/uw-cms/media'
      path: '/media'
      fullPath: '/uw-cms/media'
      preLoaderRoute: typeof UwCmsMediaRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/blog/': {
      id: '/uw-cms/blog/'
      path: '/blog'
      fullPath: '/uw-cms/blog/'
      preLoaderRoute: typeof UwCmsBlogIndexRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/blog/new': {
      id: '/uw-cms/blog/new'
      path: '/blog/new'
      fullPath: '/uw-cms/blog/new'
      preLoaderRoute: typeof UwCmsBlogNewRouteImport
      parentRoute: typeof UwCmsRoute
    }
    '/uw-cms/blog/$id/edit': {
      id: '/uw-cms/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/uw-cms/blog/$id/edit'
      preLoaderRoute: typeof UwCmsBlogIdEditRouteImport
      parentRoute: typeof UwCmsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface UwCmsRouteChildren {
  UwCmsCategoriesRoute: typeof UwCmsCategoriesRoute
  UwCmsCommentsRoute: typeof UwCmsCommentsRoute
  UwCmsLoginRoute: typeof UwCmsLoginRoute
  UwCmsMediaRoute: typeof UwCmsMediaRoute
  UwCmsIndexRoute: typeof UwCmsIndexRoute
  UwCmsBlogNewRoute: typeof UwCmsBlogNewRoute
  UwCmsBlogIndexRoute: typeof UwCmsBlogIndexRoute
  UwCmsBlogIdEditRoute: typeof UwCmsBlogIdEditRoute
}

const UwCmsRouteChildren: UwCmsRouteChildren = {
  UwCmsCategoriesRoute: UwCmsCategoriesRoute,
  UwCmsCommentsRoute: UwCmsCommentsRoute,
  UwCmsLoginRoute: UwCmsLoginRoute,
  UwCmsMediaRoute: UwCmsMediaRoute,
  UwCmsIndexRoute: UwCmsIndexRoute,
  UwCmsBlogNewRoute: UwCmsBlogNewRoute,
  UwCmsBlogIndexRoute: UwCmsBlogIndexRoute,
  UwCmsBlogIdEditRoute: UwCmsBlogIdEditRoute,
}

const UwCmsRouteWithChildren = UwCmsRoute._addFileChildren(UwCmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GetSupportRoute: GetSupportRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  StoriesRoute: StoriesRouteWithChildren,
  UwCmsRoute: UwCmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
